version: "3.3"

services:
  was-green:
    image: "${DOCKER_USERNAME}/magicconch:was-green-${GITHUB_SHA}"
    container_name: "was-green"
    build:
      context: .
      dockerfile: Dockerfile.was
    environment:
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - ACCESS_KEY_ID=${ACCESS_KEY_ID}
      - SECRET_KEY=${SECRET_KEY}
      - X_NCP_CLOVASTUDIO_API_KEY=${X_NCP_CLOVASTUDIO_API_KEY}
      - X_NCP_APIGW_API_KEY=${X_NCP_APIGW_API_KEY}
      - PORT=3002
      - SENTRY_DSN=${SENTRY_DSN}
    expose:
      - "3002"
    volumes:
      - /var/log/was:/app/was/logs
      - /var/log/typeorm:/app/was/ormLogs.log

  signal-green:
    image: "${DOCKER_USERNAME}/magicconch:signal-green-${GITHUB_SHA}"
    container_name: "signal-green"
    build:
      context: .
      dockerfile: Dockerfile.signal
    environment:
      - PORT=3003
    expose:
      - "3003"

  nginx:
    container_name: "nginx-reverse-proxy"
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - was-green
      - signal-green
      - certbot
    volumes:
      - /var/log/nginx:/var/log/nginx

  certbot:
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt
      - /var/www/html:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html -d was.tarotmilktea.com
