FROM node:20

RUN apt-get update && apt-get install -y tini

WORKDIR /app

COPY package*.json ./
RUN npm ci

WORKDIR /app/was

COPY was/package*.json ./
RUN npm ci

COPY was .
RUN npm run build

CMD ["tini", "--", "npm", "run", "start:prod"]