FROM node:20

RUN apt-get update && apt-get install -y tini

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY packages ./
RUN npm run build-prod:logger
RUN npm run build-prod:event

WORKDIR /app/was

COPY was/package*.json ./
RUN npm ci
RUN npm run move:logger && npm run move:event

COPY was .
RUN npm run build

CMD ["tini", "--", "npm", "run", "start:prod"]