FROM nginx:1.18.0

COPY config/nginx/default.conf /etc/nginx/conf.d/default.conf

COPY config/ssl/options-ssl-nginx.conf /etc/letsencrypt/options-ssl-nginx.conf
COPY config/ssl/fullchain.pem /etc/letsencrypt/live/was.tarotmilktea.com/fullchain.pem
COPY config/ssl/privkey.pem /etc/letsencrypt/live/was.tarotmilktea.com/privkey.pem
COPY config/ssl/ssl-dhparams.pem /etc/letsencrypt/ssl-dhparams.pem

CMD ["nginx", "-g", "daemon off;"]