FROM node:20

RUN apt-get update && apt-get install -y tini

WORKDIR /app/was

COPY ./was/package.json ./package.json
RUN npm install

COPY was .
RUN npm run build

CMD ["tini", "--", "npm", "run", "start:prod"]