export type HumanServerEvent = "WELCOME" | "OFFER" | "ANSWER" | "CANDIDATE" | "ROOM_FULL" | "USER_EXIT" | "HOST_EXIT" | "ROOM_CREATED" | "JOIN_ROOM_FAILED" | "JOIN_ROOM_SUCCESS" | "CREATE_ROOM_FAILED" | "CREATE_ROOM_SUCCESS";
export type HumanClientEvent = "OFFER" | "ANSWER" | "CANDIDATE" | "JOIN_ROOM" | "CREATE_ROOM";
