#!/usr/bin/env sh

. "$(dirname -- "$0")/_/husky.sh"

BRANCH=$(git rev-parse --abbrev-ref HEAD)

ALLOWED_BRANCH_PATTERN="^(BE|FE|DEVOPS|BE,FE|FE,BE)\/(feature|bugfix|hotfix|refactor)(,(feature|bugfix|hotfix|refactor))*\/#[0-9]+(-#[0-9]+)*.+$"

if ! [[ $BRANCH =~ $ALLOWED_BRANCH_PATTERN ]]; then
  echo "Error: You are not allowed to push to the branch \"$BRANCH\""
  exit 1
fi

exit 0