name: Configure PR When PR Opened

on:
  pull_request:
    types:
      - opened

jobs:
  set-label:
    name: Set Labels to PR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-request: write

    steps:
      - uses: TimonVS/pr-labeler-action@v5
        with:
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          configuration-path: .github/pr-labels.yml

  set-issue:
    name: Set Issue to PR
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          script: |
            const prTitle = context.payload.pull_request.title;
            const issueNumbers = prTitle.match(/#(\d+)/g);
            const prefix = issueNumbers ? issueNumbers.reduce((acc, curr) => acc + curr, "closed ") : '';

            github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.number,
              body: `${prefix}\n${context.payload.pull_request.body}`,
            });

            if(issueNumbers) {
              issueNumbers.forEach((num) => {
                github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: num.replace('#', ''),
                  state: 'open',
                });
              });
            }

  set-assignee:
    name: Set Assignee to PR
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          script: |
            github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.number,
              assignees: [context.payload.sender.login],
            });
