name: Release Drafter

on:
  push:
    branches:
      - release

permissions:
  contents: read

jobs:
  update-release-draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Update Release Drafter
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.ADD_TO_PROJECT_PAT }}
